In [1]:
import pandas as pd
temperature_data=pd.DataFrame({
    "city" : ["biskra","batna","alger","adrar"] ,
    "temperature" :[35,28,24,26] 
})
temperature_data

     city  temperature
0  biskra           35
1   batna           28
2   alger           24
3   adrar           26

In [2]:
windspeed_data=pd.DataFrame({
    "city" : ["biskra","batna","blida","annaba"] ,
    "windspeed" : [28,35,26,24]
})
windspeed_data

     city  windspeed
0  biskra         28
1   batna         35
2   blida         26
3  annaba         24

In [3]:
total_data=pd.merge(temperature_data , windspeed_data , on="city")  #   by defualt : how="inner"
total_data
#علاش بدا بها الترتيب بالذات ؟؟؟؟؟؟  :

     city  temperature  windspeed
0  biskra           35         28
1   batna           28         35

In [4]:
total=pd.merge(temperature_data , windspeed_data , on="city" , how="outer")
total

     city  temperature  windspeed
0   adrar         26.0        NaN
1   alger         24.0        NaN
2  annaba          NaN       24.0
3   batna         28.0       35.0
4  biskra         35.0       28.0
5   blida          NaN       26.0