In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv(r"C:\Users\GIGABYTE\OneDrive\Pictures\wather_data_02.csv")
df

        day temperature windspeed     event
0  1/1/2017        32 F     6 mph      rain
1  1/2/2017    -99999 C     7 mph     sunny
2  1/3/2017          28    -99999      snow
3  1/4/2017      -99999     7 mph  No event
4  1/5/2017        32 C    -99999      rain
5  1/6/2017        31 C     2 mph     sunny
6  1/6/2017        34 C     5 mph  No event

In [2]:
df.replace(-99999 ,np.nan ,inplace=True)
df

        day temperature windspeed     event
0  1/1/2017        32 F     6 mph      rain
1  1/2/2017    -99999 C     7 mph     sunny
2  1/3/2017          28    -99999      snow
3  1/4/2017      -99999     7 mph  No event
4  1/5/2017        32 C    -99999      rain
5  1/6/2017        31 C     2 mph     sunny
6  1/6/2017        34 C     5 mph  No event

In [3]:
df=df.replace(
    {
    "temperature" : "[A-Za-z]"   ,
    "windspeed"   : "[A-Za-z]" ,
    } ,
    " ", regex=True
    )
df

        day temperature windspeed     event
0  1/1/2017        32       6          rain
1  1/2/2017    -99999       7         sunny
2  1/3/2017          28    -99999      snow
3  1/4/2017      -99999     7      No event
4  1/5/2017        32      -99999      rain
5  1/6/2017        31       2         sunny
6  1/6/2017        34       5      No event

In [4]:
data={
    "name" : ["ahmed" , "adam" ,"isa" ,"sami"],
    "score" : ["exceptional" ,"average" ,"good" ,"poor"]
}
df=pd.DataFrame(data)
df=df.replace(["exceptional" ,"average" ,"good" ,"poor"] , [4,2,3,1])
df

    name score
0  ahmed     4
1   adam     2
2    isa     3
3   sami     1

In [5]:
df=df.replace(["isa" ,"adam"], "dodi")
df

    name score
0  ahmed     4
1   dodi     2
2   dodi     3
3   sami     1