In [1]:
import pandas as pd
algeria_wather={
    "city" : ["biskra","batna","blida","annaba"] , 
    "temperature" : [35,28,24,26] , 
    "humidity" : [7,15,20,60]
    }
df01=pd.DataFrame(algeria_wather)
df01

     city  temperature  humidity
0  biskra           35         7
1   batna           28        15
2   blida           24        20
3  annaba           26        60

In [2]:
usa_wather={
    "city" : ["new york" ,"chicago" ,"california","washington"],
    "temperature" : [28,35,26,24],
    "humidity" : [20,60,15,7],
}
df02=pd.DataFrame(usa_wather)
df02

         city  temperature  humidity
0    new york           28        20
1     chicago           35        60
2  california           26        15
3  washington           24         7

In [3]:
df=pd.concat([df01,df02])
# df=pd.concat([df01,df02] , ignore_index=True)   to ignore the index and it count 0,1,2,3,4,5,6,...
df

         city  temperature  humidity
0      biskra           35         7
1       batna           28        15
2       blida           24        20
3      annaba           26        60
0    new york           28        20
1     chicago           35        60
2  california           26        15
3  washington           24         7

In [4]:
df=pd.concat([df01,df02] , keys=["Algeria" , "USA"])
df

                 city  temperature  humidity
Algeria 0      biskra           35         7
        1       batna           28        15
        2       blida           24        20
        3      annaba           26        60
USA     0    new york           28        20
        1     chicago           35        60
        2  california           26        15
        3  washington           24         7

In [5]:
df.loc["Algeria"]

     city  temperature  humidity
0  biskra           35         7
1   batna           28        15
2   blida           24        20
3  annaba           26        60

In [6]:
temperature_data=pd.DataFrame({
    "city" : ["new york" ,"chicago" ,"california","washington"],
    "temperature" : [28,35,26,24],
})
temperature_data

         city  temperature
0    new york           28
1     chicago           35
2  california           26
3  washington           24

In [7]:
windspeed_data=pd.DataFrame({
    "city" : ["chicago" ,"new york" ,"california","washington"],
    "windspeed" : [28,35,26,24],
} ,
index=[1,0,2,3])
windspeed_data

         city  windspeed
1     chicago         28
0    new york         35
2  california         26
3  washington         24

In [8]:
df=pd.concat([temperature_data , windspeed_data["windspeed"]] , axis="columns")  #  axis="rows" : axis=0
df

         city  temperature  windspeed
0    new york           28         35
1     chicago           35         28
2  california           26         26
3  washington           24         24

In [9]:
df=pd.concat([temperature_data,windspeed_data["windspeed"]] , axis="rows")  #  axis="rows" : axis=0
df

         city  temperature  windspeed
0    new york         28.0        NaN
1     chicago         35.0        NaN
2  california         26.0        NaN
3  washington         24.0        NaN
1         NaN          NaN       28.0
0         NaN          NaN       35.0
2         NaN          NaN       26.0
3         NaN          NaN       24.0

In [10]:
event=pd.Series(["humdii","dry","rain","sunny"] , name="event")
event

0    humdii
1       dry
2      rain
3     sunny
Name: event, dtype: str

In [11]:
df=pd.concat([windspeed_data,event] , axis=1)
df

         city  windspeed   event
1     chicago         28     dry
0    new york         35  humdii
2  california         26    rain
3  washington         24   sunny