In [75]:
import pandas as pd 
df=pd.read_csv(r"C:\Users\GIGABYTE\OneDrive\Pictures\wather_data.csv"
, parse_dates=["day"])
df
# to know the type of element :
# type(df.day[1]) # pandas.Timestamp

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    rain
1 2017-01-04          NaN        9.0   sunny
2 2017-01-05         28.0        NaN    snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    rain
5 2017-01-08          NaN        NaN   sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.0        8.0  cloudy
8 2017-01-11         40.0       12.0   sunny

In [76]:
df.set_index("day" , inplace=True)
df
type(df.event["2017-01-06"])  #  NaN type is : float

float

In [77]:
# # df=df.fillna(0)   #   replace NaN values by what you want
# df=df.fillna(
#     {
#     "event" : "no event" ,
#     "temperature" : 0 ,
#     "windspeed" : 0 ,
#     }
# )
# df

In [78]:
df=df.ffill(limit=1)   # التعبىة الامامية : من الامام للاعلى 
# df=df.bfill(limit=1) # التعبىة الخلفية : من الاسفل للاعلى 
# limit : تحدد عدد مرات اللتي سوف يتم فيها تعبىة NaN
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    rain
2017-01-04         32.0        9.0   sunny
2017-01-05         28.0        9.0    snow
2017-01-06         28.0        7.0    snow
2017-01-07         32.0        7.0    rain
2017-01-08         32.0        NaN   sunny
2017-01-09          NaN        NaN   sunny
2017-01-10         34.0        8.0  cloudy
2017-01-11         40.0       12.0   sunny

In [79]:
# numeric_cols = df.select_dtypes(include='number').columns
# df[numeric_cols]=df[numeric_cols].interpolate()
# df