In [483]:
import pandas as pd

my_dict={
    "name" :     ["Ahmed","Osama","Omar","Adam","Fouad"] ,
    "language" : ["Python","JS","C++","Rust","C#"] ,
    "score" :    [75,80,95,70,90]
    }
df=pd.DataFrame(my_dict)
df

    name language  score
0  Ahmed   Python     75
1  Osama       JS     80
2   Omar      C++     95
3   Adam     Rust     70
4  Fouad       C#     90

In [484]:
df.shape

(5, 3)

In [485]:
df.head(2)

    name language  score
0  Ahmed   Python     75
1  Osama       JS     80

In [486]:
df.tail(2)

    name language  score
3   Adam     Rust     70
4  Fouad       C#     90

In [487]:
#Slicing :

df[1:4]

    name language  score
1  Osama       JS     80
2   Omar      C++     95
3   Adam     Rust     70

In [488]:
#Printing Colums :
df.columns

Index(['name', 'language', 'score'], dtype='str')

In [489]:
type(df.name)    #  pandas.Series

pandas.Series

In [490]:
#Operation on your DataFrame :

df.score.max()  #   np.int64(95)
# df.score.min()  #   np.int64(70)

np.int64(95)

In [491]:
#The mean (average) :
df.score.mean()   #   np.float64(82.0)

np.float64(82.0)

In [492]:
df["name"][df.score==df.score.max()]
# df[["language","name"]]=[df.score==df.score.max()]
# df[["name","score"]][df.language=="Python"]

2    Omar
Name: name, dtype: str

In [493]:
df.set_index("name" , inplace=True)
# df=df.set_index("name")
df

      language  score
name
Ahmed   Python     75
Osama       JS     80
Omar       C++     95
Adam      Rust     70
Fouad       C#     90

In [494]:
df.reset_index(inplace=True)
df

    name language  score
0  Ahmed   Python     75
1  Osama       JS     80
2   Omar      C++     95
3   Adam     Rust     70
4  Fouad       C#     90